langauge: python
before-install:
  - sudo apt-get update -y
  - sudo apt-get install -y curl
  - cd tmp/
  - curl –O https://repo.anaconda.com/archive/Anaconda3-2020.02-Linux-x86_64.sh
  - bash Anaconda3-2020.02-Linux-x86_64.sh
  - cd
install:
  - conda create  --name crm_validation python=3
  - conda activate crm_validation
  - make requirements
script:
  - pytest
